### PR TITLE
[BREAKING] Update to use glimmer component

### PR DESCRIPTION
**Pull request by lukemelia**
Drops support for Ember versions < 3.16

- [x] Refactor <RenderMobiledoc> component to Glimmer
- [x] Drop ember-wormhole in favor of in-element helper (via ember-in-element-polyfill)
- [x] Drop support for looking up DOM document on old Ember versions
- [x] Update dependencies
- [x] Convert tests to use Glimmer components for cards and atoms
- [x] Drop dependencies on ember-fetch, rsvp and chai
- [x] Update to reflect dropped compatibility with < 3.16

Because compatibility with Ember 4 requires ember-auto-import 2, and addons that upgrade to ember-auto-import >= 2 will only work in apps that have ember-auto-import >= 2, we will save this for a separate PR and release.

### CODE REVIEW

**Comment by donaldsonjulia** [comment]
I would love to see this get merged if there is clarification on backwards compatibility requirements. Without this update, many of our projects will be unable to upgrade due to the deprecated use of global `Ember` in `ember-wormhole@0.5.5`.

**Comment by donaldsonjulia** [comment]
I think it is fair to release a version that drops support for Ember <= 3.16. The sibling addon `ember-mobiledoc-editor` will almost certainly require dropping support for older Ember versions as part of any attempt to modernize it with Glimmer (but that's a different can of worms 🙂).

**Comment by lukemelia** [comment]
@donaldsonjulia OK, let's make it happen. I think we first need to switch to Github Actions so we can get reasonable feedback during this process. I'll start on that in a separate PR.

**Comment by lukemelia** [comment]
@donaldsonjulia If this PR looks good to you, we can merge and release a beta to try out. LMK.

**Comment by donaldsonjulia** [comment]
@lukemelia This looks great to me! I can try out a beta release as soon as it's cut and give feedback.

**Comment by lukemelia** [comment]
Released to NPM as 0.8.0-beta.0

**Comment by lukemelia** [comment]
@donaldsonjulia did you have a chance to put this release through its paces?

**Comment by donaldsonjulia** [comment]
@lukemelia Yes! It is working great so far, no issues at all -- custom cards and atoms are working as expected along with everything else.

**Comment by lukemelia** [comment]
Thanks! Promoted the beta to 0.8.0 on npm.

**Pull request merged**
